import Head from 'next/head' 
import styles from '../styles/Home.module.css' 
import Card from '../components/Card'



export default function Home() {

  // console.log(styles)
  return (
    <div className={styles.container}>
       <style jsx>
         {`
          h2{
            font-size: 38px;
          }
          h3{
            font-size: 28px;
          }
          .dummy {
            display: inline-block;
            padding: 10px;
            font-size: 24px;
            font-weight: bold;
            color: #fff;
            background-color: #007bff;
            border-radius: 8px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);
            animation: pulse 2s infinite;
          }
         
         `}
       </style>
      <Head>
        <title>Personal Beloging App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs, huntingcoder blog, hunting coder" />
        <link rel="icon" href="/favicon.ico" /> 
      </Head>
      {/* <Script src='/sc.js' strategy="lazyOnload"></Script> */}
     
      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className='dummy'>Personal Blog App is alway Present For its user To use and  Gain Knowledge in Excelent manners</span>
        
        </h1>
        <br/><br/>
        <Card/>
        <div className={styles.imagewrap}> 
{/* <Image className={styles.myImg} src="/homeimg.jfif" width={237} height={158}/> */}

        </div>
        <p className={styles.description}>
         
        </p>

      {/* <div className={`${styles1.con} ${styles2.con}`}> */}
      <div>
       
      </div>
      </main>

      <footer className={styles.footer}>
       
      </footer>
     
    </div>
  )
}
